repos:
  - repo: local
    hooks:
      - id: qmlformat
        name: qmlformat
        entry: nix develop --command qmlformat
        args: ["-i"]
        language: system
        files: \.qml$

      - id: qmllint
        name: qmllint
        entry: nix develop --command qmllint
        args: ["--unresolved-type", "info"]
        language: system
        files: \.qml$

      - id: ruff-check
        name: ruff check
        entry: nix develop --command ruff check
        args: ["--fix"]
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: nix develop --command ruff format
        language: system
        types: [python]
